apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    user: admin
    secureJsonData:
      password: password
    jsonData:
      database: automl_db
      sslmode: disable
      postgresVersion: 1500
    isDefault: true
    editable: true
